# Generated by Django 3.2.7 on 2021-09-27 15:49

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20210927_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('member_phone', models.IntegerField()),
                ('member_email', models.EmailField(max_length=254)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partner.partner')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
                'db_table': 'member',
            },
            managers=[
                ('member_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
